github:
  client_id:
    747a6bd7536c542052c2
  client_secret:
    d11bb535c330666f7c8f26afab9a3ce8a895b86d
  redirect_uri:
    http://localhost:8080/callback


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: 971003
  mvc:
    static-path-pattern=/static/**:
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lyj.community.model






